In [7]:
# Example - 1
import torch
a = torch.tensor([10,20,30,40,50,60,70,80,90,10])
print(a.reshape(2,5))

# example - 2
a = torch.arange(12)
print(a.reshape(3,4))

# Auto calculation when value is missing or wrong by pytorch
a = torch.arange(0,20,2)
print(a.reshape(5,-1))

tensor([[10, 20, 30, 40, 50],
        [60, 70, 80, 90, 10]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14],
        [16, 18]])
