In [7]:
# stack()  -->  it is used to add new dimension after combine two vectors
import torch
a = torch.tensor([1,2,3,4,5,6])
b = torch.tensor([3,4,5,6,7,8])
x = torch.stack((a,b))
print(x)

#Important Rule --->  
# dim = 0 (default)
x = torch.stack((a,b), dim = 0)
print(x)

# dim = 1
x = torch.stack((a,b), dim = 1)
print(x)

tensor([[1, 2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7, 8]])
tensor([[1, 2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7, 8]])
tensor([[1, 3],
        [2, 4],
        [3, 5],
        [4, 6],
        [5, 7],
        [6, 8]])
