In [ ]:
import torch
# zeros    it is used to generate zero for 1D, 2D, 3D, nD matrix
x = torch.zeros((2,3))
print(x)

# ones()   it is used to generate one for 1D, 2D, 3D, nD matrix
x = torch.ones((2,3))
print(x)

#rand()   it is used to generate random number between 0 to 1

x = torch.rand((2, 3))
print(x)

#randn()  it is used to generate random number(+ve or -ve) with normal distribution 
x = torch.randn((2,3))
print(x)

#randint()   it is used to generate random integer values
x = torch.randint(1,100,(2,3))
print(x)

#arange()   it is used to print the numbers similar to range function
x = torch.arange(2,8,5)
print(x)

# empty()  this function allocate the memory but not initialize
x = torch.empty(3)
print(x)

# full()   it is used to fill the same value in matrix
x = torch.full((2,3), 10)
print(x)

# linspace()   it is used to print space equaly
x = torch.linspace(0,10,5)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.7956, 0.0837, 0.3993],
        [0.9441, 0.7575, 0.1796]])
tensor([[ 1.5073, -0.7945, -0.8834],
        [ 0.3873, -0.3046,  2.4587]])
tensor([[94, 28, 25],
        [83, 12, 14]])
tensor([2, 7])
tensor([2.3694e-38, 3.6013e-43, 0.0000e+00])
tensor([[10, 10, 10],
        [10, 10, 10]])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
