In [4]:
# Normal Boolean indexing that is give the output in true or false

import torch
a = torch.tensor([10,20,30,40,50,60,70])
print(a > 40)


# Actual Boolean indexing that give exact value according to the condition

a = torch.tensor([10,20,30,40,50,60,70])
print(a[a>40])
print(a[a % 2 == 0])

tensor([False, False, False, False,  True,  True,  True])
tensor([50, 60, 70])
tensor([10, 20, 30, 40, 50, 60, 70])
