In [11]:
# Slicing...... it is used to access the multiple values

import torch
x = torch.tensor([10,20,30,40,50,60])
print(x[:4])
print(x[1:])
print(x[::])
print(x[1:4])

# for 2D....
x = torch.tensor([[10,20,30],[40,50,60]])
#print(x[0:1])
#print(x[-1:])
# first raw
print(x[1,:])
# first column
print(x[:,0])
# second column
print(x[:,1])
#third column
print(x[:,2])

tensor([10, 20, 30, 40])
tensor([20, 30, 40, 50, 60])
tensor([10, 20, 30, 40, 50, 60])
tensor([20, 30, 40])
tensor([40, 50, 60])
tensor([10, 40])
tensor([20, 50])
tensor([30, 60])
